$id = isset($_GET['id'])?$_GET['id']: "573ib1kp5nk92irinpumbo9krlb";
$t=time();
$s=substr(md5($id."151".$t.'TtJSg@2g*$K4PjUH'),0,8);
$res = file_get_contents("https://pc.api.btime.com/video/play?from=pc&callback=&id=".$id."&type_id=151&timestamp=".$t."&sign=".$s);
$data = json_decode($res);
$e = $data->data->video_stream[0]->stream_url;
$a=str_split($e);
$b=array_reverse($a);
$bb=implode($b);
$c=base64_decode($bb);
$d=base64_decode($c);
echo $d;
header('location:'.$d);